FINAL JOB-READY CHALLENGE
━━━━━━━━━━━━━━━━━━

You are working as a Junior Data Analyst in a hospital.

The manager gives you this requirement:

"Identify patients who need further review based on their age, admission type, operation duration and hospital stay."

Create your own logic using:

• Age
• Admission_Type
• Operation_Duration_Min
• Length_of_Stay_Days

Your solution must:

1. Filter the required patients.
2. Select only relevant columns.
3. Sort the result by operation duration.
4. Identify the patient with the longest operation.
5. Display the final result clearly.

In [1]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [4]:
df.loc[(df["Age"]>50)&(df["Admission_Type"]=="Emergency")&(df["Operation_Duration_Min"].idxmax())&(df["Length_of_Stay_Days"].idxmax())][["Patient_ID","City","Surgery_Type"]]

  Patient_ID       City Surgery_Type
1       P102   Warangal         CABG
5       P106  Nizamabad         PTCA